### ISSUE TITLE
Як ты там?

### ISSUE THREAD

**Issue by OlehKulykov** [tim-kozak/redux-rails#41]
Everything is worked as expected.

**Comment by tim-kozak** [comment]
Hah really worked out fine?
Haven't tested this for a while))

я живий здоровий, ти як?

**Comment by OlehKulykov** [comment]
та какож більш-менш, балакав тiк-що зi своїми, одного із школи вже нема, ще не привезли.

**Comment by tim-kozak** [comment]
страшні речі
